
# ---------------------- Deployment ---------------------- #

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: podcount
spec:
   replicas: 2
   template:
     metadata:
       labels:
         run: podcounter
     spec:
      containers:
        - name: podcounter
          image: murali44/podcounter
          ports:
          - containerPort: 8080
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace

---

# -------------------------- Service -------------------------- #

apiVersion: v1
kind: Service
metadata:
  name: podcount
  labels:
    run: podcounter
spec:
  type: NodePort
  ports:
  - port: 8080
    protocol: TCP
  selector:
    run: podcounter
  